name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 101
          swap-size-mb: 200
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          overprovision-lvm: 'true'

      - name: remove even more
        run: |
            sudo apt-get purge -y \
              '^llvm-.*' \
              'php.*' \
              '^mongodb-.*' \
              '^mysql-.*' \
              azure-cli \
              google-chrome-stable \
              firefox \
              powershell \
              microsoft-edge-stable \
              mono-devel
            sudo apt-get autoremove -y
            sudo apt-get clean
      - uses: actions/checkout@v4

      - name: Download file from Sciebo
        env:
          SCIEBO_USERNAME: ${{ secrets.SCIEBO_USERNAME }}
          SCIEBO_PASSWORD: ${{ secrets.SCIEBO_PASSWORD }}
        run: |
          sudo apt install device-tree-compiler expect -y
          chmod +x init_OHD.sh
          ./init_OHD.sh "$SCIEBO_USERNAME" "$SCIEBO_PASSWORD"

      - name: Fix ownership before build
        run: |
          sudo chown -R $(whoami):$(id -gn) ${{ github.workspace }}
      
      - name: build
        run: |
          echo "BR2_ROOTFS_DEVICE_CREATION_DYNAMIC_MDEV=y" >> buildroot/.config
          echo "BR2_FAKEROOT=y" >> buildroot/.config
          ./build.sh

      - name: Zip the output directory
        run: |
            zip -r output.zip output
      
      - name: Upload zipped output
        uses: actions/upload-artifact@v4
        with:
          name: output.zip
          path: output.zip