name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download file from Sciebo
        env:
          SCIEBO_USERNAME: ${{ secrets.SCIEBO_USERNAME }}
          SCIEBO_PASSWORD: ${{ secrets.SCIEBO_PASSWORD }}
        run: |
          sudo apt install device-tree-compiler expect -y
          chmod +x init_OHD.sh
          ./init_OHD.sh "$SCIEBO_USERNAME" "$SCIEBO_PASSWORD"

      - name: Fix ownership before build
        run: |
          sudo docker load
          sudo docker run -it --rm buildroot-env:fully-loaded bash -c "/buildroot/build.sh"

      - name: build
        run: |
          echo "BR2_ROOTFS_DEVICE_CREATION_DYNAMIC_MDEV=y" >> buildroot/.config
          echo "BR2_FAKEROOT=y" >> buildroot/.config
          ./build.sh

      - name: Zip the output directory
        run: |
            zip -r output.zip output
      
      - name: Upload zipped output
        uses: actions/upload-artifact@v4
        with:
          name: output.zip
          path: output.zip
